# КВБО-01-21 Марченко Сергей

# 1.3.1
## Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами

In [10]:
import numpy as np


matrix = np.tile(np.array([[0, 1], [1, 0]]), [4, 4])
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 1.3.2
## Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arange.

In [16]:
import numpy as np


matrix = np.zeros((5, 5), dtype=int) + np.arange(5)
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
