# КВБО-01-21 Марченко Сергей

# 1.3.1
## Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами

In [10]:
import numpy as np


matrix = np.tile(np.array([[0, 1], [1, 0]]), [4, 4])
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 1.3.2
## Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arange.

In [16]:
import numpy as np


matrix = np.zeros((5, 5), dtype=int) + np.arange(5)
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 1.3.3
## Создать массив 3x3x3 со случайными значениями.

In [17]:
import numpy as np


rng = np.random.default_rng()
array = rng.random((3, 3, 3))
print(array)

[[[0.07605166 0.91849519 0.16989987]
  [0.04946346 0.92780858 0.76556587]
  [0.62007802 0.44622348 0.08067212]]

 [[0.61413026 0.34080184 0.74434198]
  [0.69792751 0.08684613 0.49523601]
  [0.43092813 0.93257328 0.42591935]]

 [[0.1604034  0.03422533 0.66546531]
  [0.15917693 0.2810526  0.31061194]
  [0.96060867 0.44557854 0.11266511]]]


# 1.3.4
## Создать матрицу с 0 внутри, и 1 на границах.

In [18]:
import numpy as np


matrix = np.ones((10, 10), dtype=int)
matrix[1:-1,1:-1] = 0
print(matrix)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


# 1.3.5
## Создайте массив и отсортируйте его по убыванию.

In [19]:
import numpy as np


rng = np.random.default_rng()
array = rng.random(10)
array.sort()
array = np.flip(array)
print(array)

[0.95513142 0.93011153 0.90073439 0.79053736 0.64109622 0.43687724
 0.41316295 0.4050575  0.29621197 0.23545035]
