# КВБО-01-21 Марченко Сергей

# 1.3.1
## Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами

In [10]:
import numpy as np


matrix = np.tile(np.array([[0, 1], [1, 0]]), [4, 4])
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 1.3.2
## Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arange.

In [16]:
import numpy as np


matrix = np.zeros((5, 5), dtype=int) + np.arange(5)
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 1.3.3
## Создать массив 3x3x3 со случайными значениями.

In [17]:
import numpy as np


rng = np.random.default_rng()
array = rng.random((3, 3, 3))
print(array)

[[[0.07605166 0.91849519 0.16989987]
  [0.04946346 0.92780858 0.76556587]
  [0.62007802 0.44622348 0.08067212]]

 [[0.61413026 0.34080184 0.74434198]
  [0.69792751 0.08684613 0.49523601]
  [0.43092813 0.93257328 0.42591935]]

 [[0.1604034  0.03422533 0.66546531]
  [0.15917693 0.2810526  0.31061194]
  [0.96060867 0.44557854 0.11266511]]]


# 1.3.4
## Создать матрицу с 0 внутри, и 1 на границах.

In [18]:
import numpy as np


matrix = np.ones((10, 10), dtype=int)
matrix[1:-1,1:-1] = 0
print(matrix)

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


# 1.3.5
## Создайте массив и отсортируйте его по убыванию.

In [19]:
import numpy as np


rng = np.random.default_rng()
array = rng.random(10)
array.sort()
array = np.flip(array)
print(array)

[0.95513142 0.93011153 0.90073439 0.79053736 0.64109622 0.43687724
 0.41316295 0.4050575  0.29621197 0.23545035]


# 1.3.6
## Создайте матрицу, выведите ее форму, размер и размерность.

In [20]:
import numpy as np


rng = np.random.default_rng()
shape = tuple(rng.integers(1, 6, 2))
matrix = rng.integers(0, 2, shape)

form = "Square"
if shape[0] == 1 and shape[1] > 1:
    form = "Vector-row"
elif shape[0] > 1 and shape[1] == 1:
    form = "Vector-column"
elif shape[0] != shape[1]:
    form = "Rectangle"   

print(f"Matrix:\n{matrix}")
print(f"Form: {form}")
print(f"Size: {matrix.size}")
print(f"Dimensions: {shape[0]}x{shape[1]}")

Matrix:
[[0 0 0]
 [1 0 0]]
Form: Rectangle
Size: 6
Dimensions: 2x3


# 2.3.1
## Найдите евклидово расстояние между двумя Series (точками) a и b, не используя встроенную формулу.

In [21]:
import pandas as pd
import numpy as np


a = pd.Series([4, 5])
b = pd.Series([1, 6])
print(np.sqrt(np.abs(a[0] - b[0])**2 + np.abs(a[1] - b[1])**2))

3.1622776601683795


# 2.3.2
## Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных.


In [32]:
import pandas as pn


url = 'https://raw.githubusercontent.com/akmand/datasets/main/abolone.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   

   Viscera weight  Shell weight  Rings  
0          0.1010         0.150     15  
1          0.0485         0.070      7  
2          0.1415         0.210      9  
3          0.1140         0.155     10  
4          0.0395         0.055      7

# 2.3.3
## Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.


In [43]:
import pandas as pn
from IPython.core.interactiveshell import InteractiveShell


# Tell jupyter notebook to display all outputs instead of the last one
InteractiveShell.ast_node_interactivity = "all"

url = 'https://raw.githubusercontent.com/akmand/datasets/main/abolone.csv'
dataframe = pd.read_csv(url)

# 2.2.5
dataframe.head(5)
dataframe.tail(5)
dataframe.shape
dataframe.describe()

# 2.2.6
dataframe.iloc[1000:1005]

# 2.2.7
dataframe[dataframe['Rings'] == 7].head(5)

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   

   Viscera weight  Shell weight  Rings  
0          0.1010         0.150     15  
1          0.0485         0.070      7  
2          0.1415         0.210      9  
3          0.1140         0.155     10  
4          0.0395         0.055      7

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
4172      F   0.565     0.450   0.165        0.8870          0.3700   
4173      M   0.590     0.440   0.135        0.9660          0.4390   
4174      M   0.600     0.475   0.205        1.1760          0.5255   
4175      F   0.625     0.485   0.150        1.0945          0.5310   
4176      M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
4172          0.2390        0.2490     11  
4173          0.2145        0.2605     10  
4174          0.2875        0.3080      9  
4175          0.2610        0.2960     10  
4176          0.3765        0.4950     12

(4177, 9)

Length     Diameter       Height  Whole weight  Shucked weight  \
count  4177.000000  4177.000000  4177.000000   4177.000000     4177.000000   
mean      0.523992     0.407881     0.139516      0.828742        0.359367   
std       0.120093     0.099240     0.041827      0.490389        0.221963   
min       0.075000     0.055000     0.000000      0.002000        0.001000   
25%       0.450000     0.350000     0.115000      0.441500        0.186000   
50%       0.545000     0.425000     0.140000      0.799500        0.336000   
75%       0.615000     0.480000     0.165000      1.153000        0.502000   
max       0.815000     0.650000     1.130000      2.825500        1.488000   

       Viscera weight  Shell weight        Rings  
count     4177.000000   4177.000000  4177.000000  
mean         0.180594      0.238831     9.933684  
std          0.109614      0.139203     3.224169  
min          0.000500      0.001500     1.000000  
25%          0.093500      0.130000     8.000000  
50%          0.171000      0.234000     9.000000  
75%          0.253000      0.329000    11.000000  
max          0.760000      1.005000    29.000000

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
1000      F   0.595     0.450   0.150        1.1140          0.5865   
1001      M   0.595     0.475   0.165        1.2130          0.6210   
1002      F   0.595     0.460   0.140        1.0045          0.4655   
1003      M   0.595     0.455   0.150        1.0440          0.5180   
1004      F   0.605     0.490   0.150        1.1345          0.5265   

      Viscera weight  Shell weight  Rings  
1000          0.2205        0.2500     11  
1001          0.2435        0.2740      9  
1002          0.2095        0.2515      9  
1003          0.2205        0.2700      9  
1004          0.2645        0.2950      9

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
1       M   0.350     0.265   0.090        0.2255          0.0995   
4       I   0.330     0.255   0.080        0.2050          0.0895   
16      I   0.355     0.280   0.085        0.2905          0.0950   
18      M   0.365     0.295   0.080        0.2555          0.0970   
45      I   0.390     0.295   0.095        0.2030          0.0875   

    Viscera weight  Shell weight  Rings  
1           0.0485         0.070      7  
4           0.0395         0.055      7  
16          0.0395         0.115      7  
18          0.0430         0.100      7  
45          0.0450         0.075      7

# 3.3.2
## Загрузить фрейм данных по ссылке: https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. Необходимо выполнить нормализацию первого числового признака (sepal_length_cm) с использованием минимаксного преобразования, а второго (sepal_width_cm) с задействованием z-масштабирования.

In [57]:
import pandas as pn
from sklearn import preprocessing

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)

dataframe[['sepal_length_cm']] = preprocessing.MinMaxScaler().fit_transform(dataframe[['sepal_length_cm']])
dataframe[['sepal_width_cm']] = preprocessing.StandardScaler().fit_transform(dataframe[['sepal_width_cm']])

dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]